# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Node.js, GitHub Actions, and Azure App Service: https://aka.ms/node-webapps-actions

name: Build and deploy Node.js app to Azure Web App - Ayanami

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build application (if needed)
        run: npm run build --if-present

      - name: Create deployment package
        run: |
          # Remove files not needed for deployment
          rm -rf node_modules/.cache
          rm -rf .git
          rm -rf .github
          # Create a clean package
          zip -r ../deployment.zip . -x "*.git*" "*.github*" "node_modules/.cache/*"
        shell: bash

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ../deployment.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Extract deployment package
        run: |
          unzip -q deployment.zip
          rm deployment.zip
          ls -la

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_98AC94F437944CD6A609A94070CA8B6F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0FF2A983C0D34C1CBF875282C6FA3935 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2BDE90B58E6A4970B21023DAFAB66C2A }}

      - name: Run pre-deployment script
        run: |
          chmod +x pre-deploy.sh
          ./pre-deploy.sh
        shell: bash

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'Ayanami'
          slot-name: 'Production'
          package: .
          clean: true

      - name: Verify deployment
        run: |
          echo "Deployment completed. Verifying..."
          # Wait a moment for the app to start
          sleep 30
          # Try to get the health endpoint
          curl -f https://ayanami.azurewebsites.net/health || echo "Health check failed - app may still be starting"
          